import 'package:projeto_magazine/models/goods.dart';

List<Goods> listOfGoods = [
  Goods(
    name: "Smartphone Samsung Galaxy A71" "128GB Azul 6GB RAm",
    description: "Tela 6,7° Câm. Quádrupla Câm. + selfie 32MP",
    parcel: "10x de RS 197,99 sem juros",
    photo: "assets/celular.jpg",
    value: "R\$ 1.979,97",
    isFavorite: true,
  ),
  Goods(
    name: "Geladeira Brastemp Frost Free Duplex Evox",
    description: "375L BRM45 HKANA",
    parcel: "10x de RS 269,80 sem juros",
    photo: "assets/geladeira.jpg",
    value: "R\$ 2.698,00",
    isFavorite: false,
  ),
  Goods(
    name: "Fritadeira Elétrica sem óleo/Air Fryer Nell Smart",
    description: "Preta 2,4L com timer",
    parcel: "5x de R\$ 45,98 sem juros",
    photo: "assets/fritadeira.jpg",
    value: "R\$ 229,90",
    isFavorite: false,
  ),
  Goods(
    name: "PC Gamer Neologic Start NLI81426 Ryzen 3 2200G 8GB",
    description: "Radeon Vega 8 integrado + SSD 240GB",
    parcel: "12x de R\$ 404,92 sem juros",
    photo: "assets/computador.jpg",
    value: "R\$ 4.859,00",
    isFavorite: true,
  ),
  Goods(
    name: "Microfone de Mesa Condensador para Celular,Computador e Notebook",
    description: "Redshock",
    parcel: "3x de R\$ 33,30 sem juros",
    photo: "assets/microfone.jpg",
    value: "R\$ 99,90",
    isFavorite: false,
  ),
  Goods(
    name: "Ventilador de Parede e Mesa Mondial Maxi Power",
    description: "NV-15-6P-FB 30cm 3 Velocidades",
    parcel: "2x de R\$ 44,95 sem juros",
    photo: "assets/ventilador.jpg",
    value: "R\$ 89,90",
    isFavorite: true,
  ),
  Goods(
    name: "Drone Multilaser Eagle FPV",
    description: "Câmera HD Flips 360",
    parcel: "12x de R\$ 185,16 sem juros",
    photo: "assets/drone.jpg",
    value: "R\$ 2.222,00",
    isFavorite: false,
  ),
];
